name: build and push test
on: 
  push: 
    branches: main
    tags:
    - 'v*'
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: fangziyue/workshop:${{ github.ref_name }}
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send custom JSON data to Slack workflow
      uses: tokorom/action-slack-incoming-webhook@main
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Name: Fang Ziyue"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "Matriculation: A0243820M"
                }, 
                "text": {
                  "type": "mrkdwn",
                  "text": "e0838388@u.nus.edu"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.repositoryUrl }}"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "fangziyue/workshop:${{ github.ref_name }}"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "Image url: https://hub.docker.com/repository/docker/fangziyue/workshop"
                }
              }
          }
            ]
          }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
