name: build and push test
on: 
  push: 
    branches: main
    tags:
    - 'v*'
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: fangziyue/workshop:${{ github.ref_name }}
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send custom JSON data to Slack workflow
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: "name: Fang Ziyue\nMatriculation:A0243820M\nemail\n${{ github.repositoryUrl }}\nImageName:fangziyue/workshop:${{ github.ref_name }}\nImage url:https://hub.docker.com/repository/docker/fangziyue/workshop"
          
